### ISSUE TITLE
Fix issues w/ missing IDs in MAM results

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#11]
This breaks MAM loading in the Web app

**Comment by nesium** [comment]
The plan here is to make the ID optional. This however will require the different UI implementations to disable features which require a message ID. Notably "Edit message", "Delete message", "Add reaction".

**Comment by valeriansaliou** [comment]
Noted, will do now.

**Comment by nesium** [comment]
`Message.id` is now optional

**Comment by valeriansaliou** [comment]
Let's try this w/ the core-client path override system!
