### ISSUE TITLE
Implement missing IQ responders

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#13]
Some IQ responders are quite standard for XMPP clients, which don't seem to be implemented there. See the list of responders in the TS IQ event handler of the Web app: https://github.com/prose-im/prose-app-web/blob/master/src/broker/events/iq.ts#L58 for reference, and associated NS constant values: https://github.com/prose-im/prose-app-web/blob/master/src/broker/stanzas/xmlns.ts

- NS_PING
- NS_TIME
- NS_LAST
- NS_DISCO_INFO
- NS_VERSION

Also, not sure if this is done, but in case the client receives an unsupported IQ, it should answer as such: https://github.com/prose-im/prose-app-web/blob/master/src/broker/events/iq.ts#L188

Those should also be announced in CAPS. The TS Web app broker auto-announces all NS located in https://github.com/prose-im/prose-app-web/blob/master/src/broker/stanzas/xmlns.ts, which is what other clients also do. You can be verbose and announce everything that's supported by the client, even features that can't be queried by other clients.

**Comment by nesium** [comment]
The mentioned IQ requests are now all handled. We also have an easy way to simulate an incoming stanza and write a snapshot test for the expected response [here](https://github.com/prose-im/prose-core-client/blob/710ec1e63a3825039cd9ee8a18951c6e0fbf8dba/crates/prose-core-client/tests/handle_iq_requests.rs).

The only missing functionality is the `feature-not-implemented` response for unsupported IQs which I'm tracking in #17.
