### ISSUE TITLE
IQ with `urn:xmpp:time` NS gets double-answered with answer and error

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#16]
![unvl](https://github.com/prose-im/prose-core-client/assets/1451907/ecf7686a-d278-42de-aeb9-6b9f1df78e66)

Sounds like the `service-unavailable` should not kick in there?

**Comment by nesium** [comment]
That doesn't look like a response from the core lib. Look at the id starting with `purple`. Is that coming from Strophe.JS?

**Comment by nesium** [comment]
My bad. Still seems related to [this Strophe.JS feature](https://github.com/strophe/strophejs/blob/a1a9e418a49dee56e6c42a1b67be118e7cd3f5bc/src/connection.js#L274).

**Comment by valeriansaliou** [comment]
Fixed in: https://github.com/prose-im/prose-app-web/commit/ca8cbe5a508bf364ce783c695f536de5d888163d ; Strophe needs to have a handler somewhere return `true` to make it think that the stanza was processed. Added this for all stanza types.

**Comment by nesium** [comment]
Thanks!
