### ISSUE TITLE
Message structure date is always the same

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#41]
I noticed an issue since a few core client releases already, where the `date` value for a `Message` would always be set to `2023-07-17T09:40:48.746Z`.

Looks like some hardcoded test value was not reverted back to the dynamic message date value in the Rust code, or am I wrong?

**Comment by valeriansaliou** [comment]
Indeed: https://github.com/prose-im/prose-core-client/blob/master/bindings/prose-sdk-js/src/types/message.rs#L64

**Comment by nesium** [comment]
Oh, wow. That looks like a refactoring artifact. It would be really nice to somehow generate these mappings automatically.
