### ISSUE TITLE
Toggling favorite status of a private group does nothing

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#42]
When calling `SidebarItem::toggleFavorite()` for a private group, the `isFavorite` variable of the `SidebarItem` instance for the private group never gets `true`, even after a full reload/reconnect.

It however works just fine for DMs and public channels (private channels untested).

This can easily be tested from the Web App, clicking on the topbar star icon when hovering the group name in the topbar.

**Comment by nesium** [comment]
That should be fixed by 8b05d6e743206af33cfd0f5458bbe1e0e44ded88. Please reopen in case you still see this.
