### ISSUE TITLE
Do not send received/read receipts?

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-core-client#44]
Currently I'm sending a received marker ([XEP-0333](https://xmpp.org/extensions/xep-0333.html)) for every received message. This leads to a bit of back and forth and `messagesUpdated` events when these are exchanged.

I've added this during a time when I didn't know about Stream Management (#21) and thought of it as a replacement (which it isn't since Stream Management works for all kinds of stanzas).

I'm not sure if we even need message markers. WhatsApp has them, Slack to my knowledge hasn't. What do you think @valeriansaliou?

**Comment by valeriansaliou** [comment]
We don't need them, no workspace app sends read receipts. You can safely remove them.
