### ISSUE TITLE
MUC participants querying on join is quite spammy (queries could maybe be grouped)

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#47]
Currently, when joining 1 channel, the client sends 3 IQs for each available affiliation value. This can be quite spammy when you're a member of a lot of channels/groups. I think this could be optimized, knowing how the MUC IQ-based querying protocol works.

IQs currently sent as a result of joining a MUC:

```xml
<iq id="1cdf8769-b7fa-4f75-92d2-9adbbf9779a6" to="org.prose.channel.g9y1znlb@groups.prose.org.local" type="get" xmlns="jabber:client"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="owner" xmlns="http://jabber.org/protocol/muc#user"/></query></iq>

<iq id="1e5f43c8-bc11-4ce0-83b6-5d7c61d19504" to="org.prose.channel.g9y1znlb@groups.prose.org.local" type="get" xmlns="jabber:client"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="member" xmlns="http://jabber.org/protocol/muc#user"/></query></iq>

<iq id="9bd18a48-41a5-4590-9788-57ddf0aaf878" to="org.prose.channel.g9y1znlb@groups.prose.org.local" type="get" xmlns="jabber:client"><query xmlns="http://jabber.org/protocol/muc#admin"><item affiliation="admin" xmlns="http://jabber.org/protocol/muc#user"/></query></iq>
```

Could probably be grouped into one, as such:

```xml
<iq id="1cdf8769-b7fa-4f75-92d2-9adbbf9779a6" to="org.prose.channel.g9y1znlb@groups.prose.org.local" type="get" xmlns="jabber:client">
  <query xmlns="http://jabber.org/protocol/muc#admin">
    <item affiliation="owner" xmlns="http://jabber.org/protocol/muc#user"/>
    <item affiliation="member" xmlns="http://jabber.org/protocol/muc#user"/>
    <item affiliation="admin" xmlns="http://jabber.org/protocol/muc#user"/>
  </query>
</iq>
```

Looking at XEP-0045, I believe this is possible, since you can `set` multiple items at once.

**Comment by nesium** [comment]
That was my first thought as well, alas it doesn't work. There is a fair amount of ambiguity in the XEPs and even in the contained XSDs.

I believe that the consensus is that if a scenario is not explicitly described it will not be implemented. Here's a related discussion from the ejabberd project: https://github.com/processone/ejabberd/issues/3258

**Comment by valeriansaliou** [comment]
Argh… okay let’s close this then.
