### ISSUE TITLE
Ability to know if a message was edited

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-client#48]
In order to show an "(edited)" suffix in the message view (per-message), I'd need an "edited" boolean field in the `Message` structure.

Note: more of such "meta" fields might come in the future, eg. `encrypted<boolean>`, so it could be nested in a shared sub-structure of `Message`, eg. `MessageMetas`.

**Comment by nesium** [comment]
I've added a struct `MessageMetadata` with a flag `isEdited` and renamed `metas` to `meta` since `metadata` is uncountable and thus doesn't have a plural form 🤓

**Comment by valeriansaliou** [comment]
Thank you 🙏🏻 That was fast!

**Comment by valeriansaliou** [comment]
Re-opening since it doesn’t seem to set the flag to true if edited, I guess it’s still WIP?

**Comment by valeriansaliou** [comment]
Sorry, my bad, when looking at the code it looked like there was no logic to set the `isEdited` flag to `true` when relevant, only the model, but I was wrong. It's now implemented & working!
