### ISSUE TITLE
xmpp.org: Host doap file for client represenation

### ISSUE THREAD

**Issue by Echolon** [prose-im/prose-core-client#7]
Hi,

to better advertise your client on https://xmpp.org/software/clients/ I would like to recommend to host a doap file.

Find a good example: https://github.com/conversejs/converse.js/blob/master/conversejs.doap
Entry here: https://github.com/xsf/xmpp.org/blob/master/data/clients.json#L327

**Comment by valeriansaliou** [comment]
Thank you, will do :)

**Comment by valeriansaliou** [comment]
Done at: https://github.com/prose-im/prose-core-client/blob/master/prose.doap

**Comment by Echolon** [comment]
@valeriansaliou I realized your client does not have had a release yet right? Is it under active development? Does it make sense to list actually?

**Comment by valeriansaliou** [comment]
It's still in development yes, at: https://github.com/prose-im/prose-app-macos (macOS app as a starter).

**Comment by Echolon** [comment]
Ah alright. I would say, once it has been released, let's place it - okay?

**Comment by valeriansaliou** [comment]
Works for me, thank you :)

**Comment by Echolon** [comment]
Hi,

great stuff!

would you also create a PR at xmpp.org repo?

Aug 13, 2023 8:05:41 AM Valerian Saliou ***@***.***>:

**Comment by valeriansaliou** [comment]
Hi @Echolon 

Since Prose is now available for download, I'd like to request to re-open the MR at: https://github.com/xsf/xmpp.org/pull/1322 :)

Thanks!
