### ISSUE TITLE
Unavailable server component prevents login

### ISSUE THREAD

**Issue by truenicoco** [prose-im/prose-core-client#73]
Having offline components on your server prevents authenticating to the server.

<img width="1055" alt="Capture d’écran 2024-04-14 à 09 15 49" src="https://github.com/prose-im/prose-core-client/assets/1313576/62d7acf0-3c44-4237-8ebc-27b55651bf99">

I believe these errors should just be dismissed.

**Comment by nesium** [comment]
Hi @truenicoco. That should work after the next release.
