### ISSUE TITLE
Fetch avatar of non-contacts

### ISSUE THREAD

**Issue by truenicoco** [prose-im/prose-core-client#78]
~Using my standard prosody instance, I don't see any avatar via the prose web app. I think that prose uses XEP-0292 (vcard4) to set and fetch users avatars, but this is not the usual practice of other clients (which rely on XEP-0084).~

EDIT: my bad, prose seems to use XEP-0084 but only for contacts in the roster. While being subscribed to the presence of a contact is a condition to receive 'live avatar updates', I believe it would be nice to attempt to fetch the non-contacts avatars too (if the XEP-0084 nodes are configured to be publicly fetchable).

No avatar in groups either, but it's related to https://github.com/prose-im/prose-core-client/issues/50

**Comment by valeriansaliou** [comment]
Definitely! It's something that's known, we need to improve the way that vCard are handled in general and provide backwards compatibility for non-vCard 4 avatars in general.
