### ISSUE TITLE
Prose doesn't authenticate against servers implementing XEP-0474 (SASL SCRAM Downgrade Protection)

### ISSUE THREAD

**Issue by rom1dep** [prose-im/prose-core-client#87]
More on the subject of how it may affect other clients be read here: https://www.process-one.net/blog/ejabberd-24-02/#converse 

In short, prose fails to authenticate against recent ejabberd or prosody server whenever disable_sasl_scram_downgrade_protection: true is set (ejabberd) or with https://modules.prosody.im/mod_sasl_ssdp.html (prosody).

**Comment by nesium** [comment]
Thanks @rom1dep for reporting! I've moved the ticket to prose-app-web which introduces the strophe.js dependency, thus closing the issue here.
