### ISSUE TITLE
Support XHTML-IM

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-core-client#88]
<img width="800" alt="Screenshot 2024-06-18 at 17 40 06" src="https://github.com/prose-im/prose-core-client/assets/39174/b0aa4b82-0d04-4514-a636-27a6d423ff07">

<img width="800" src="https://github.com/prose-im/prose-core-client/assets/39174/f2779e79-3997-4033-8b2d-b1ef78140cef">

https://xmpp.org/extensions/xep-0071.html

Refs prose-im/prose-core-views#20

**Comment by nesium** [comment]
Closing this in favor of #79. We'll go for XEP-0394 for now.

**Comment by sjehuda** [comment]
Related to #109, because PubSub, as Atom Over XMPP, allows to deliver XHTML.
